<?php

$review_title = array(
	'Great!',
	'Excellent!',
	'Most Useful App Ever',
	'5 STARS!',
	'Genius Idea',
	'This one is BRILLIANT!',
	'Awesome app, I love it!',
	"That's right.",
	"That's the way.",
	"Nice going.",
	"That's coming along nicely.",
	"That's great.",
	"Great.",
	"Fantastic.",
	"Terrific.",
	"Good work.",
	"That's better.",
	"Excellent.",
	"Good job.",
	"Awesome.",
	"Good going.",
	"Keep it up.",
	"That's really nice.",
	"Wow.",
	"Keep up the good work.",
	"Much better.",
	"Good for you.",
	"That's very much better.",
	"Good thinking.",
	"Exactly right.",
	"Super.",
	"Nice going.",
	"I've never seen anyone do it better.",
	"Way to go.",
	"Not bad.",
	"Superb.",
	"Wonderful.",
	"That's the way to do it.",
	"Keep on trying.",
	"That's it.",
	"That's good.",
	"That's the way to do it.",
	"That's better than ever.",
	"That's quite an improvement.",
	"That kind of work makes me happy.",
	"Marvelous.",
	"Perfect.",
	"That's not bad at all.",
	"Fine.",
	"That's it.",
	"Well done.",
	"Tremendous.",
	"Outstanding.",
	"I like that.",
	"Now that's what I call a fine job.",
	"Congratulations.",
	"That was first class work.",
	"Right on.",
	"Sensational.",
	"That's the best ever.",
	"Good remembering.",
	"That's live.",
	"Congratulations.",
);

$review_body = array(
	'This app is very useful. I like it very much!',
	'It worths every cent I\'ve spend. Really a nice one!',
	'This app helps me a lot. I would give it 6 stars if I could.',
	'Useful, helpful, and graceful!',
	'Interesting and helpful. This app can do exactly what I want, which is super cool!',
	'Don’t defile your beautifully designed iPhone or iPod touch with substandard, poorly implemented, ugly software :)',
	'It looks like a quality time-waster. Good job',
	'Great idea! It has tons of potential to be a fun way to snag some balls or whatever you call it.',
	'I do not review many apps, but for this one, the name is funny enough and the app is good enough that it’s worth a review.',
	'I’d like to tell you that there’s more than what it is described, but that would make me a big fat liar! Anyway it just does whatever it said and that is good enough for me already. Grab it while you can!',
	"You’re on the right track now!",
	"You’ve got it made. SUPER!",
	"That’s right!",
	"That’s good. You are very good at that.",
	"That’s coming along nicely. GOOD WORK!",
	"I’m happy to see the app like this.",
	"Exactly right.",
	"You’ve just about got it.",
	"You’re doing a good job.",
	"THAT’S IT!",
	"That’s quite an improvement.",
	"GREAT!",
	"Congratulations!",
	"Not bad.",
	"Keep working on it.",
	"Now you have it!",
	"Good for you!",
	"Couldn’t have done it better myself.",
	"Aren’t you proud of yourself? One more time and you’ll have it.",
	"You really make my job fun.",
	"That’s the right way to do it.",
	"You’re getting better every day.",
	"You did it that time!",
	"That’s not half bad.",
	"Nice going.",
	"You haven’t missed a thing!",
	"WOW!",
	"That’s the way!",
	"Keep up the good work.",
	"TERRIFIC!",
	"Nothing can stop you now.",
	"That’s the way to do it.",
	"SENSATIONAL!",
	"That’s better.",
	"That was first class work.",
	"EXCELLENT!",
	"That’s the best ever.",
	"You’ve just about mastered it.",
	"PERFECT!",
	"That’s better than ever.",
	"Much better!",
	"WONDERFUL!",
	"You must have been practicing.",
	"You did that very well.",
	"FINE!",
	"Nice going.",
	"You’re really going to town.",
	"OUTSTANDING!",
	"FANTASTIC!",
	"TREMENDOUS!",
	"That’s how to handle that.",
	"Now that’s what I call a fine job.",
	"That’s great.",
	"Right on!",
	"ou’re really improving.",
	"You’re doing beautifully!",
	"SUPERB!",
	"Good remembering.",
	"You’ve got that down pat.",
	"Keep it up!",
	"Congratulations.",
	"You got it right! Well look at you go.",
	"That’s it.",
	"I like knowing this app. MARVELOUS!",
	"I like that.",
	"Way to go!",
	"Now you have the hang of it. You’re doing fine!",
	"Good thinking.",
	"You are really learning a lot.",
	"Good going. I’ve never seen app do it better.",
	"Good for you!",
	"That’s a good kick! I think you’ve got it now.",
	"Good job, man!",
	"That’s really nice.",
	"I think you’re doing the right thing.",
	"The concept of this game is very simple, but it's funny to play with friends and give 'em a beatdown! Of course I won't play it when I have plenty of time, but hey, it's an extremely good option when I have 1 or 2 minutes to kill. It takes several seconds for a single round, and after a few rounds, the train/bus comes. Helpful and funny!",
);

?>
